version: "3.9"

services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data # cert storage
      - ./data/config:/config
    environment:
      # Optional but recommended for ACME notifications
      - ACME_AGREE=true
